[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-s",
    "-C", "link-arg=EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']",
    "-C", "link-arg=-s",
    "-C", "link-arg=EXPORTED_FUNCTIONS=['_malloc', '_free', '_add', '_validate']",
]
