name: Run

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Node tests
        run: |
          npm --prefix javascript/ install
          npm --prefix javascript/ run test

      - name: Build webapp docker
        run: docker buildx build --platform=linux/amd64 -t ipfs-boot .

      - name: Build webapp
        id: build_webapp
        run: |
          docker run --rm -i --platform=linux/amd64 -v ./dist:/root/dist ipfs-boot | tee out.txt
          cidv0=$(cat out.txt | grep CIDv0 | awk '{print $3}')
          cidv1=$(cat out.txt | grep CIDv1 | awk '{print $3}')
          echo "cidv0=$cidv0" >> $GITHUB_OUTPUT
          echo "cidv1=$cidv1" >> $GITHUB_OUTPUT

      - name: Build wasm docker
        run: docker buildx build --platform=linux/amd64 -f Dockerfile.wasm -t ipfs-wasm .

      - name: Build wasm
        id: build_wasm
        run: |
          docker run --rm -i --platform=linux/amd64 -v ./dist:/root/dist ipfs-wasm
          sha256_wasm=$(sha256sum dist/nitro_wasm.wasm | awk '{print $1}')
          sha256_js=$(sha256sum dist/nitro_wasm.js | awk '{print $1}')
          echo "sha256_wasm=$sha256_wasm" >> $GITHUB_OUTPUT
          echo "sha256_js=$sha256_js" >> $GITHUB_OUTPUT

      - name: Check wasm
        run: |
          sha256sum dist/nitro_wasm.wasm >> hash.txt
          sha256sum javascript/assets/nitro_wasm.wasm >> hash.txt
          sha256sum --check hash.txt || exit 1
          echo "WASM ok"
          sha256sum dist/nitro_wasm.js >> hash.txt
          sha256sum javascript/assets/nitro_wasm.js >> hash.txt
          sha256sum --check hash.txt || exit 1
          echo "WASM JS ok"

      - name: Summary
        run: |
          echo "Build ok"
          echo "Hash wasm = ${{ steps.build_wasm.outputs.sha256_wasm }}"
          echo "Hash wasm js = ${{ steps.build_wasm.outputs.sha256_js }}"
          echo "CIDv0 = ${{ steps.build_webapp.outputs.cidv0 }}"
          echo "CIDv1 = ${{ steps.build_webapp.outputs.cidv1 }}"
          echo "Build ok:" >> $GITHUB_STEP_SUMMARY
          echo "+ Hash wasm = ${{ steps.build_wasm.outputs.sha256_wasm }}" >> $GITHUB_STEP_SUMMARY
          echo "+ Hash wasm js = ${{ steps.build_wasm.outputs.sha256_js }}" >> $GITHUB_STEP_SUMMARY
          echo "+ CIDv0 = ${{ steps.build_webapp.outputs.cidv0 }}" >> $GITHUB_STEP_SUMMARY
          echo "+ CIDv1 = ${{ steps.build_webapp.outputs.cidv1 }}" >> $GITHUB_STEP_SUMMARY

      - name: Zip
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          docker buildx build --platform=linux/amd64 -t ipfs-boot .
          docker run --rm -i --platform=linux/amd64 -v ./dist:/root/dist ipfs-boot | tee out.txt

      - name: Check CIDv0
        run: |
          a=$(cat out.txt | grep CIDv0 | awk '{print $3}')
          b=$(cat README.md | grep CIDv0 | awk '{print $4}')
          bash -c '[ "$a" == "$b" ]' || exit 1
          echo "CIDv0 ok"
          echo "$a $b"

      - name: Check CIDv1
        run: |
          a=$(cat out.txt | grep CIDv1 | awk '{print $3}')
          b=$(cat README.md | grep CIDv1 | awk '{print $4}')
          bash -c '[ "$a" == "$b" ]' || exit 1
          echo "CIDv1 ok"
          echo "$a $b"

      - name: Check Href 1
        run: |
          a=$(cat README.md | grep dweb.link | grep done | awk '{print $3}')
          b=$(cat out.txt | grep CIDv1 | awk '{print $3}')
          b="https://$b.ipfs.dweb.link"
          bash -c '[ "$a" == "$b" ]' || exit 1
          echo "Href 1 ok"
          echo "$a $b"

      - name: Check Href 2
        run: |
          a=$(cat README.md | grep dweb.link | grep choo | awk '{print $3}')
          b=$(cat out.txt | grep CIDv1 | awk '{print $3}')
          b="https://$b.ipfs.dweb.link"
          bash -c '[ "$a" == "$b" ]' || exit 1
          echo "Href 2 ok"
          echo "$a $b"
