name: Run

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check cert
        run: |
          mkdir download && cd download/
          curl https://aws-nitro-enclaves.amazonaws.com/AWS_NitroEnclaves_Root-G1.zip > root.zip
          unzip root.zip
          sha256sum root.pem > hash.txt
          sha256sum ../javascript/assets/root.pem >> hash.txt
          sha256sum --check hash.txt || exit 1

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Test node
        run: |
          npm --prefix javascript/ install
          npm --prefix javascript/ run test

      - name: Build webapp
        run: |
          docker buildx build --platform=linux/amd64 -t ipfs-boot .
          docker run --rm -i --platform=linux/amd64 -v ./dist:/root/dist ipfs-boot | tee out.txt

      - name: Check CIDv0
        run: |
          a=$(cat out.txt | grep CIDv0 | awk '{print $3}')
          b=$(cat README.md | grep CIDv0 | awk '{print $4}')
          bash -c '[[ "$1" == "$2" ]]' _ "$a" "$b" || exit 1

      - name: Check CIDv1
        run: |
          a=$(cat out.txt | grep CIDv1 | awk '{print $3}')
          b=$(cat README.md | grep CIDv1 | awk '{print $4}')
          bash -c '[[ "$1" == "$2" ]]' _ "$a" "$b" || exit 1

      - name: Check Link 1
        run: |
          a=$(cat README.md | grep dweb.link | grep done | awk '{print $3}')
          b=$(cat out.txt | grep CIDv1 | awk '{print $3}')
          b="https://$b.ipfs.dweb.link"
          bash -c '[[ "$1" == "$2" ]]' _ "$a" "$b" || exit 1

      - name: Check Link 2
        run: |
          a=$(cat README.md | grep dweb.link | grep choo | awk '{print $3}')
          b=$(cat out.txt | grep CIDv1 | awk '{print $3}')
          b="https://$b.ipfs.dweb.link"
          bash -c '[[ "$1" == "$2" ]]' _ "$a" "$b" || exit 1

      - name: Build wasm
        run: |
          docker buildx build --platform=linux/amd64 -f Dockerfile.wasm -t ipfs-wasm .
          docker run --rm -i --platform=linux/amd64 -v ./dist:/root/dist ipfs-wasm

      - name: Check wasm
        run: |
          sha256sum dist/nitro_wasm.wasm > hash.txt
          sha256sum javascript/assets/nitro_wasm.wasm >> hash.txt
          sha256sum --check hash.txt || exit 1
          sha256sum dist/nitro_wasm.js > hash.txt
          sha256sum javascript/assets/nitro_wasm.js >> hash.txt
          sha256sum --check hash.txt || exit 1

      - name: Zip
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
